export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAILED = 'GET_CHARACTERS_FAILED';
export const SORT_IN_ASCENDING_ORDER = 'SORT_IN_ASCENDING_ORDER';
export const SORT_IN_DESCENDING_ORDER = 'SORT_IN_DESCENDING_ORDER';
